export const USER_AUTHORIZE = 'USER_AUTHORIZE';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_FETCH_CATEGORY = 'USER_FETCH_CATEGORY';

export const ADMIN_AUTHORIZE = 'ADMIN_AUTHORIZE';
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';
export const ADMIN_SAVE_CATEGORY = 'ADMIN_SAVE_CATEGORY';
export const ADMIN_SAVE_PRODUCT = 'ADMIN_SAVE_PRODUCT';

export const CART_SAVE_TO_STORE = 'CART_SAVE_TO_STORE';
